Few merged changes and a temp commit of new order API (Not tested)
Accelerate-net/vegaAggregator pull request #53
Opened 2022-05-23 15:46 UTC by Firoz-PS

2022-06-17 12:11 UTC, abhijithcs requested changes

2022-06-17 12:11 UTC, abhijithcs commented on resources/acceleron-server/routes/OrderRoute.js
> +    const data = await new OrderController(req).newOrder();
How different from:
KOTController(req).createNewKOT();

2022-06-17 12:11 UTC, abhijithcs commented on resources/acceleron-server/routes/KOTRoute.js
> +    const data = await new KOTController(req).createNewKOT();
How different from:
OrderController(req).newOrder();

2022-06-17 12:11 UTC, abhijithcs commented on resources/acceleron-server/models/OrderModel.js
> +        '/accelerate_kot/_design/kot-fetch/_view/fetchbytable?startkey=["' +
Keep it in single line

2022-06-17 12:12 UTC, abhijithcs requested changes

2022-06-17 12:12 UTC, abhijithcs commented on resources/acceleron-server/services/OrderService.js
> +    data = await this.SummaryService.getAllBillingParameters().catch((error) => {
Don't keep it data - may be more meaningful name say, bilingParamsData..

2022-06-17 17:29 UTC, abhijithcs requested changes

2022-06-17 17:29 UTC, abhijithcs commented on resources/acceleron-server/routes/OrderRoute.js
> +router.put("/saved/clear", async function (req, res, next) {
/clearall

2022-06-17 17:29 UTC, abhijithcs commented on resources/acceleron-server/routes/OrderRoute.js
> +// TO BE IMPLEMENTED
Remove

2022-06-17 17:29 UTC, abhijithcs commented on resources/acceleron-server/routes/OrderRoute.js
> +// TO BE IMPLEMENTED
Remove

2022-06-17 17:29 UTC, abhijithcs commented on resources/acceleron-server/services/OrderService.js
> +    newHoldingOrder.timestamp = moment().format("HHmm");
Move moment().format("HHmm"); to TimeUtils.js

2022-06-17 17:29 UTC, abhijithcs commented on resources/acceleron-server/services/OrderService.js
> +      //renderCustomerInfo()
Add //TODO

2022-07-10 18:03 UTC, Firoz-PS commented on resources/acceleron-server/routes/SettingsRoute.js
> +router.put("/:id", async function (req, res, next) {
In OrderService for updating kot index and clearing all saved orders data

2022-07-10 18:03 UTC, Firoz-PS commented on resources/acceleron-server/services/SettingsService.js
> +    async updateSettingsById(settings_id, new_entry) {
In OrderService for updating kot index and clearing all saved orders data

2022-07-10 18:13 UTC, Firoz-PS commented on resources/acceleron-server/routes/OrderRoute.js
> +    const data = await new OrderController(req).newOrder();
This involves other preprocesses as well

2022-07-10 18:14 UTC, Firoz-PS commented on resources/acceleron-server/routes/KOTRoute.js
> +    const data = await new KOTController(req).createNewKOT();
This doesn't involve the preprocesses for creating the kot object

2022-09-03 05:45 UTC, abhijithcs approved these changes

2022-09-03 05:45 UTC, merged