migrated checkForRequests-processor.js
Accelerate-net/vegaAggregator pull request #65
Opened 2022-06-24 16:19 UTC by zeus-12

2022-06-24 18:11 UTC, abhijithcs commented on resources/acceleron-server/controllers/BootstrapController.js
> +
Move the changes to new:
AggregationController / AggregationService / AggregationModel

and path,  
/aggregation/
    ../action-request/

2022-06-24 18:11 UTC, abhijithcs commented on resources/acceleron-server/models/BootstrapModel.js
> +class BootstrapModel extends BaseModel {
Move changes to AggregationModel

2022-06-24 18:12 UTC, abhijithcs commented on resources/acceleron-server/routes/BootstrapRoute.js
> +router.get('/initialise-processing', async function (req, res, next) {
Move to AggregationRoute with base path  'aggregation' in route/index.js
and /action-request/ (for fetch all)

2022-06-24 18:13 UTC, abhijithcs commented on resources/acceleron-server/routes/BootstrapRoute.js
> +router.delete('/action_request/:ID', async function (req, res, next) {
rename as /action-request/

2022-06-24 18:14 UTC, abhijithcs commented on resources/acceleron-server/routes/BootstrapRoute.js
> +})
There should be two more routes:
 GET /action-request/{id} ===> to fetch given action request
 POST /action-request/ ===> to create a new action request

2022-06-24 18:14 UTC, abhijithcs commented on resources/acceleron-server/services/BootstrapService.js
>  class BootstrapService extends BaseService {
Move the changes to AggregationService.js

2022-06-24 18:14 UTC, abhijithcs commented on resources/acceleron-server/services/BootstrapService.js
> +    async listenRequest() {
Rename

2022-06-24 18:16 UTC, abhijithcs commented on resources/acceleron-server/services/BootstrapService.js
> +        let kotData = await this.KOTService.getKOTById(kotId).catch((error) => { throw error })
Move this KOTData out from backend. Let front end call KOT while processing the requests. Otherwise if there are 25 requests, in each forLoop call we'll un-necessarily send all the KOTdata everytime.

2022-06-24 20:27 UTC, zeus-12 commented on resources/acceleron-aggregator/core/processor.js
> +
not there initially.

2022-06-25 16:27 UTC, abhijithcs requested changes

2022-06-25 16:27 UTC, abhijithcs commented on resources/acceleron-server/services/common/AuthService.js
> +      machine : 'server'
machineCustomName

2022-06-25 16:27 UTC, abhijithcs commented on resources/acceleron-server/utils/TimeUtils.js
> +function getDate() {
getCurrentDate()

2022-06-25 16:35 UTC, abhijithcs requested changes

2022-06-25 16:35 UTC, abhijithcs commented on resources/acceleron-server/utils/ErrorConstants.js
> +ErrorType.action_request_data_missing =  'Please provide all required data!';
data ==> details

2022-06-25 16:38 UTC, abhijithcs requested changes

2022-06-25 16:38 UTC, abhijithcs commented on resources/acceleron-server/services/AggregationService.js
> +        var requestData = actionRequestData.rows[0]?.value
Return them all

2022-06-25 16:38 UTC, abhijithcs commented on resources/acceleron-server/services/AggregationService.js
> +        let { KotNo, action, table} = actionRequestFile
Keep a check for actionType

2022-06-25 17:01 UTC, abhijithcs approved these changes

2022-06-25 17:01 UTC, merged